version: '3'
services:

  app:
    tty: true
    image: node:8.11
    ports:
      - "${APP_PORT-5675}:${APP_PORT-5675}"
    working_dir: /app
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    depends_on:
      - mongo
    restart: on-failure
    entrypoint: node_modules/.bin/gulp
    environment:
      NODE_ENV: development
      PORT: ${APP_PORT-5675}
      MONGO_DSN: ${MONGO_DSN-mongodb://mongo:27017/graphql-server}

  mongo:
    image: mongo:3.6
    command: --quiet
    volumes:
      - mongodb:/data/db
    ports:
      - "${APP_DB_PORT-5676}:27017"

volumes:
  node_modules: {}
  mongodb: {}
